# Python 3
We assume you are using Python 3 in this course.

## Question 1

You've learned different data types in Python. Now, let's test your knowledge. 

You need to use f-strings to format strings. 

Write a program using the "f-strings" (https://realpython.com/python-f-strings/) and the input() function to convert temperatures from Fahrenheit to Celsius. [Formula: Celsius = (Fahrenheit - 32)*5/9]

Hint: you may need int() or float() function

An example program output:
```
Please enter the temperature in Fahrenheit: 140
140F is 60.0 in Celsius. 
```

In [5]:
# an example of f-strings and the input() function
username = input('What\'s your name? ')
print(f'Welcome, {username}!')

Welcome, Li!


In [6]:
# complete your program here
f = input('Please enter the temperature in Fahrenheit: ')
f = int(f)
c = (f-32)*5/9
print(f'{f}F is {c} in Celsius.')

140F is 60.0 in Celsius.


Now, do the opposite by converting temperatures from Celsius to Fahrenheit.
Another example:
```
Please enter the temperature in Celsius: 60
60C is 140.0 in Fahrenheit. 
```

In [7]:
# complete your program here
c = input('Please enter the temperature in Celsius: ')
c = int(c)
f = c*9/5+32
print(f'{c}C is {f} in Fahrenheit.')

60C is 140.0 in Fahrenheit.


Next, let's make it a bit challenging by adding conditional statements to convert temperatures between Celsius and Fahrenheit. [Formula: Celsius/5 = (Fahrenheit - 32)/9]

An example program output:
```
Please enter the temperature: 60
Is this in Celsius or Fahrenheit? C
60C is 140 in Fahrenheit
```

Another example:
```
Please enter the temperature: 140
Is this Celsius or Fahrenheit? F
140F is 60 in Celsius
```

In [8]:
# complete your program here
d = input('Please enter the temperature: ')
m = input('Is this in Celsius or Fahrenheit? ')
d = int(d)
if m=='C' or m=='c': 
    x = d*9/5+32
    print(f'{d}C is {x} in Fahrenheit.')
elif m=='F' or m=='f': 
    x = (d-32)*5/9
    print(f'{d}F is {x} in Celsius.')
else:
    print("Wrong inputs. ")

60C is 140.0 in Fahrenheit.


## Question 2

Have some fun with strings.

In [9]:
sentence = "Talk is cheap. Show me the code - Linus Torvalds"

In [10]:
# Find the length of this sentence.
len(sentence)

48

In [11]:
# Convert the whole string to lower case. 
sentence.lower()

'talk is cheap. show me the code - linus torvalds'

In [12]:
# Extract a substring from the 10th character from left to the 10th character from right.
sentence[9:-9]

'heap. Show me the code - Linus'

In [13]:
# Split the sentence into a list of substrings by space ' '. 
sentence.split()

['Talk', 'is', 'cheap.', 'Show', 'me', 'the', 'code', '-', 'Linus', 'Torvalds']

In [14]:
# Given the sentence, output a list of words in lowercase (without symbols such as '.' and '-'). 
sentence.lower().replace('.','').replace('-','').split()

['talk', 'is', 'cheap', 'show', 'me', 'the', 'code', 'linus', 'torvalds']

In [15]:
# Count the total number of vowels in the sentence.
vows = 0
for c in sentence.lower():
    if c in 'aeiou':
        vows +=1
vows

13

In [16]:
vows = 0
for v in 'aeiou':
    vows += sentence.lower().count(v)
vows

13

In [17]:
# Find the positions (indices) of all vowels in the sentence. 
vow_index = []
for i in range(len(sentence)): 
    if sentence.lower()[i] in 'aeiou':
        vow_index.append(i)
vow_index

[1, 5, 10, 11, 17, 21, 25, 28, 30, 35, 37, 41, 44]

## Question 3

Review list comprehension if needed: https://realpython.com/list-comprehension-python/

The formula for list comprehension is: `new_list = [expression for member in iterable (if conditional)]`

You need to do the following:

In [18]:
# Use a loop to create a list of 5 cube numbers and print the list: [0, 1, 8, 27, 64]
cubes = []
for i in range(5):
    cubes.append(i**3)
cubes

[0, 1, 8, 27, 64]

In [19]:
# Use list comprehension to create the same list
cubes = [i**3 for i in range(5)]
cubes

[0, 1, 8, 27, 64]

In [20]:
# Find the positions (indices) of all vowels in a sentence using list comprehension
sentence = "Toto, I\'ve a feeling we\'re not in Kansas anymore. - THE WIZARD OF OZ (1939)"
[i for i in range(len(sentence)) if sentence.lower()[i] in 'aeiou']

[1,
 3,
 6,
 9,
 11,
 14,
 15,
 17,
 22,
 25,
 28,
 31,
 35,
 38,
 41,
 45,
 47,
 54,
 57,
 59,
 63,
 66]

In [21]:
# Use a loop to create a list of first n numbers in the Fibonacci sequence
# [0, 1, 1, 2, 3, 5, 8, ...] 
fibonacci = []
n = input('How many numbers do you want? ')
# add your code here
n=int(n)
for i in range(n): 
    if i==0: 
        fibonacci.append(0)
    elif i==1: 
        fibonacci.append(1)
    else:
        fibonacci.append(fibonacci[i-2]+fibonacci[i-1])
fibonacci

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34]

## Question 4

This question is about Python dictionaries.

|Vaccine|Efficacy|
|-----|-------|
|Pfizer|95%|
|Moderna|95%|
|AstraZeneca|72%|
|Johnson & Johnson|66%|

Source: https://www.biospace.com/article/comparing-covid-19-vaccines-pfizer-biontech-moderna-astrazeneca-oxford-j-and-j-russia-s-sputnik-v/

In [22]:
# Create a dictionary to save the data of vaccines and their efficacy. (save 95% as 0.95)
v_dict = {'Pfizer': .95,
          'Moderna': .95,
          'AstraZeneca': .72,
          'Johnson & Johnson': .66
}

In [23]:
v = input('Which vaccine? ')
# print the efficacy of the vaccine
print(v_dict[v])

0.95


In [24]:
# add another vaccine 'Sputnik V' with 91.4% efficacy rate to the dictionary
v_dict['Sputnik V']=.914

In [25]:
# add another vaccine 'Sinovac' with 50.38% efficacy rate to the dictionary
v_dict['Sinovac']=.5038

In [26]:
# Print vaccines with efficacy lower than 90%.
for v in v_dict:
    if v_dict[v]<.9:
        print(v)

AstraZeneca
Johnson & Johnson
Sinovac


In [27]:
# delete the Sinovac vaccine from the dictionary. 
del v_dict['Sinovac']

In [28]:
# Count the occurrence of each letter (excluding spaces) in this sentence. 
sentence = 'the quick brown fox jumps over the lazy dog'

# Save the result in a dictionary 
ch_dict = {} 
# Use a loop to iterate all characters
for c in sentence.replace(' ',''): 
    if c not in ch_dict:
        ch_dict[c] = 1
    else: 
        ch_dict[c] += 1
print(ch_dict)

{'t': 2, 'h': 2, 'e': 3, 'q': 1, 'u': 2, 'i': 1, 'c': 1, 'k': 1, 'b': 1, 'r': 2, 'o': 4, 'w': 1, 'n': 1, 'f': 1, 'x': 1, 'j': 1, 'm': 1, 'p': 1, 's': 1, 'v': 1, 'l': 1, 'a': 1, 'z': 1, 'y': 1, 'd': 1, 'g': 1}


## Question 5

Next, we will practice with NumPy arrays.  

In [29]:
import numpy as np

In [30]:
# create a 1-D array of first 20 positive even numbers (starting with 2)
np.array([2*(i+1) for i in range(20)])

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40])

In [31]:
np.arange(2, 42, 2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40])

In [32]:
# create a 1-D array of first 20 positive odd numbers (starting with 1)
np.array([2*i+1 for i in range(20)])

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39])

In [33]:
np.arange(1, 41, 2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39])

In [34]:
# create a 10x10 array in the following format: 
# first row: [0,1,...,9]
# second row: [10,11,...,19]
# ...
# tenth row: [90,91,...,99]
np.array([range(i*10, i*10 + 10) for i in [k for k in range(10)]])


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [35]:
# Create a 10x10 array of normally distributed random values
# with mean 0 and standard deviation 1
M = np.random.normal(0, 1, (10, 10))
M

array([[ 1.19675514, -0.54970795, -1.43806512,  2.16998467,  1.54103614,
         0.91967369, -0.98255726,  0.60234983, -1.39145039,  0.8026563 ],
       [-1.57034093,  0.60726243,  1.15923931, -1.30576873, -1.96869401,
        -2.22675127,  1.48377679,  0.98095533,  0.15170297, -1.17034403],
       [-1.86302187, -1.09417864,  1.00574645,  0.24760086,  0.85975877,
         1.81771455,  0.18417592, -0.40758151,  0.78371761,  0.78327574],
       [-2.06430742,  0.22219942,  0.43397788, -0.07827459, -0.6430045 ,
        -0.21021271, -0.49949668, -1.06973413, -0.12129836,  0.1152306 ],
       [ 0.48297935, -1.21063902, -1.15811603, -0.26011254, -1.55004398,
        -0.01766668,  1.30649019,  0.63477375,  0.97349107,  0.47800203],
       [-0.24789587,  0.75856591,  1.16088203, -1.43726295, -0.04943784,
        -0.14221058,  1.40976226, -0.21528503,  1.3323104 ,  0.08180408],
       [ 0.32028327, -0.99130183, -0.92996788,  0.62835113, -0.1313938 ,
        -0.90999601,  0.58865675,  0.49192045

In [36]:
M.shape

(10, 10)

In [37]:
# Count the numbers in M with an absolute value greater than 1.
count = 0
for i in range(M.shape[0]):
    for j in range(M.shape[1]):
        if np.abs(M[i,j])>1:
            count += 1
count

32

In [38]:
abs(M)>1

array([[ True, False,  True,  True,  True, False, False, False,  True,
        False],
       [ True, False,  True,  True,  True,  True,  True, False, False,
         True],
       [ True,  True,  True, False, False,  True, False, False, False,
        False],
       [ True, False, False, False, False, False, False,  True, False,
        False],
       [False,  True,  True, False,  True, False,  True, False, False,
        False],
       [False, False,  True,  True, False, False,  True, False,  True,
        False],
       [False, False, False, False, False, False, False, False, False,
         True],
       [ True,  True, False, False,  True, False, False, False, False,
        False],
       [False, False, False, False, False, False,  True, False, False,
        False],
       [False, False, False, False, False, False, False, False,  True,
        False]])

In [39]:
np.count_nonzero(abs(M)>1)

32

In [40]:
(abs(M)>1).sum()

np.int64(32)

In [41]:
# Reference: https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html

# Input the number of rows (input an integer >= 3)
r = input('Row count: ')

# Input the number of columns (input another integer >= 3)
c = input('column count: ')

# Hint: you may want to use the function int().
r = int(r)
c = int(c)
# Create a r x c array of random integers between 10 (inclusive) and 20 (exclusive).
arr = np.random.randint(10, 20, size=(r, c))
arr

array([[11, 15, 10, 19, 15, 12, 17, 13, 14, 13],
       [11, 10, 17, 16, 15, 17, 19, 10, 15, 16],
       [17, 14, 13, 12, 15, 15, 15, 16, 11, 19],
       [18, 18, 16, 17, 18, 15, 13, 18, 11, 18],
       [18, 18, 15, 13, 10, 14, 13, 14, 18, 16]], dtype=int32)

In [42]:
# output the element in the first row and the third column
arr[0,2]

np.int32(10)

In [43]:
# output the element in the second row and the last column
arr[1,-1]

np.int32(16)

In [44]:
# output the second row of the array
arr[1]

array([11, 10, 17, 16, 15, 17, 19, 10, 15, 16], dtype=int32)

In [45]:
# output the second-to-last row of the array
arr[-2]

array([18, 18, 16, 17, 18, 15, 13, 18, 11, 18], dtype=int32)

In [46]:
# output the second column of the array
arr[:,1]

array([15, 10, 14, 18, 18], dtype=int32)

In [47]:
# output the second-to-last column of the array
arr[:,-2]

array([14, 15, 11, 11, 18], dtype=int32)

In [48]:
# output the upper-left 3x3 sub-array
arr[:3,:3]

array([[11, 15, 10],
       [11, 10, 17],
       [17, 14, 13]], dtype=int32)

In [49]:
# output the bottom-left 3x3 sub-array
arr[-3:,:3]

array([[17, 14, 13],
       [18, 18, 16],
       [18, 18, 15]], dtype=int32)

In [50]:
# output the upper-right 3x3 sub-array
arr[:3,-3:]

array([[13, 14, 13],
       [10, 15, 16],
       [16, 11, 19]], dtype=int32)

In [51]:
# output the bottom-right 3x3 sub-array
arr[-3:,-3:]

array([[16, 11, 19],
       [18, 11, 18],
       [14, 18, 16]], dtype=int32)

In [52]:
# Create a 1-D array from 1 to 50 (inclusive)
A = np.arange(1, 51)
# Reshape A to a 5x10 array in the following format: 
# first row: [1,...,10]
# second row: [11,...,20]
# ...
# fifth row: [41,...,50]
A = A.reshape([5,10])
A

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [53]:
# add a row [51,...,60] to A
new = np.arange(51,61)
A = np.vstack([A, new])
A

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60]])

In [54]:
# split the new A (6x10) to two 3x10 arrays A1 and A2
A1 = A[:3,:]
A2 = A[-3:,:]
print(A1)
print(A2)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]
[[31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]
 [51 52 53 54 55 56 57 58 59 60]]


In [55]:
# Add 10 to each element of A
A+10

array([[11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
       [61, 62, 63, 64, 65, 66, 67, 68, 69, 70]])

In [56]:
# Calculate the square root of each element in A
np.sqrt(A)

array([[1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
        2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766],
       [3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
        4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595],
       [4.58257569, 4.69041576, 4.79583152, 4.89897949, 5.        ,
        5.09901951, 5.19615242, 5.29150262, 5.38516481, 5.47722558],
       [5.56776436, 5.65685425, 5.74456265, 5.83095189, 5.91607978,
        6.        , 6.08276253, 6.164414  , 6.244998  , 6.32455532],
       [6.40312424, 6.4807407 , 6.55743852, 6.63324958, 6.70820393,
        6.78232998, 6.8556546 , 6.92820323, 7.        , 7.07106781],
       [7.14142843, 7.21110255, 7.28010989, 7.34846923, 7.41619849,
        7.48331477, 7.54983444, 7.61577311, 7.68114575, 7.74596669]])

In [57]:
# Above, we have created a 10x10 array M of normally distributed random values
# with mean 0 and standard deviation 1
M.shape

(10, 10)

In [58]:
# Print the mean, standard deviation of all numbers in M
print(np.mean(M))
print(np.std(M))

0.05548325560505953
0.9766914964921937


In [59]:
# Print the maximum, 3rd quartile, median, 1st quartile, and minimum in M
print("Max:               ", np.max(M))
print("75th percentile:   ", np.percentile(M, 75))
print("Median:            ", np.median(M))
print("25th percentile:   ", np.percentile(M, 25))
print("Min:               ", np.min(M))

Max:                2.8512371337665168
75th percentile:    0.7647433659448173
Median:             0.08916960071918076
25th percentile:    -0.6246493128704302
Min:                -2.2267512696668827
